"""Heston calibration to an implied-vol surface by least squares on the COS pricer.

The objective is the vector of implied-vol residuals `iv_model(K, T) − iv_market(K, T)`
(vega-weighting in price space is the same thing to first order and is what a desk quotes),
solved with `scipy.optimize.least_squares` (trust-region reflective, bounds enforced:
v0, kappa, theta, sigma_v > 0, −1 < rho < 1). Starting points matter for Heston — the
kappa–sigma_v–theta directions are nearly flat on a surface with few maturities — so the
default runs a small multi-start and returns the best fit with every start's result kept.

What the tests establish and the caller should know:

* on a noise-free surface generated by known parameters the fit recovers them (rho and v0
  tightly, kappa/theta/sigma_v to the extent the surface identifies them — the report
  carries the RMSE in vol points and a Feller-condition flag, not just five numbers);
* the residual, not the parameters, is the deliverable: two parameter sets 20 % apart in
  kappa can price the same surface to 1e-4 in vol; a calibration that reports parameters
  without the fit error is not a calibration.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

import numpy as np
from scipy.optimize import least_squares

from . import bs
from .heston import HestonParams, price_strikes

BOUNDS_LO = np.array([1e-4, 1e-3, 1e-4, 1e-3, -0.999])
BOUNDS_HI = np.array([4.0, 50.0, 4.0, 5.0, 0.999])
DEFAULT_STARTS = (
    HestonParams(0.04, 2.0, 0.04, 0.4, -0.6),
    HestonParams(0.09, 1.0, 0.06, 0.8, -0.3),
    HestonParams(0.02, 5.0, 0.03, 0.3, -0.8),
)


@dataclass(frozen=True)
class Surface:
    """Market implied vols on a (K, T) grid, all for one spot, rate and dividend yield."""
    S: float
    r: float
    q: float
    K: np.ndarray        # strikes, shape (n,)
    T: np.ndarray        # maturities in years, shape (n,)
    iv: np.ndarray       # implied vols, shape (n,)

    @staticmethod
    def from_params(S: float, r: float, q: float, strikes: Sequence[float], maturities: Sequence[float],
                    p: HestonParams, N: int = 512) -> "Surface":
        """Model surface: price every (K, T) with COS and invert to Black-Scholes vol."""
        K = np.array([k for _ in maturities for k in strikes], dtype=float)
        T = np.array([t for t in maturities for _ in strikes], dtype=float)
        iv = model_ivs(S, r, q, K, T, p, N)
        return Surface(S, r, q, K, T, iv)


def model_ivs(S: float, r: float, q: float, K: np.ndarray, T: np.ndarray, p: HestonParams, N: int = 512) -> np.ndarray:
    """One characteristic-function evaluation per maturity; out-of-the-money side inverted (better conditioned)."""
    out = np.empty(len(K))
    for t in np.unique(T):
        idx = np.flatnonzero(T == t)
        for right, sel in (("P", idx[K[idx] < S]), ("C", idx[K[idx] >= S])):
            if len(sel):
                px = price_strikes(S, K[sel], float(t), right, p, r, q, N=N)
                out[sel] = bs.implied_vol_vec(px, S, K[sel], float(t), right, r, q)
    return out


@dataclass(frozen=True)
class CalibrationResult:
    params: HestonParams
    rmse_vol: float                 # root mean square residual, vol points (0.001 = 0.1 vol pt)
    max_abs_vol: float
    feller: bool                    # 2 kappa theta > sigma_v^2
    n_points: int
    n_evaluations: int
    starts: tuple[dict, ...] = field(default_factory=tuple)   # every start's (params, rmse) for the caller to see
    residuals: np.ndarray | None = None

    def summary(self) -> str:
        p = self.params
        return (f"v0={p.v0:.4f} kappa={p.kappa:.3f} theta={p.theta:.4f} sigma_v={p.sigma_v:.3f} rho={p.rho:.3f} | "
                f"RMSE {self.rmse_vol * 100:.3f} vol pts, max {self.max_abs_vol * 100:.3f}, n={self.n_points}, "
                f"Feller {'ok' if self.feller else 'VIOLATED'}, {self.n_evaluations} surface evaluations")


def _unpack(x: np.ndarray) -> HestonParams:
    return HestonParams(*(float(v) for v in x))


def calibrate(surface: Surface, starts: Sequence[HestonParams] = DEFAULT_STARTS, N: int = 512,
              weights: np.ndarray | None = None, max_nfev: int = 200) -> CalibrationResult:
    """Least squares in implied-vol space over the whole surface, best of `starts`."""
    w = np.ones(len(surface.iv)) if weights is None else np.asarray(weights, dtype=float)
    finite = np.isfinite(surface.iv)
    if finite.sum() < 5:
        raise ValueError("need at least 5 finite implied vols to fit 5 parameters")
    K, T, iv, w = surface.K[finite], surface.T[finite], surface.iv[finite], w[finite]
    evals = 0

    def resid(x):
        nonlocal evals
        evals += 1
        m = model_ivs(surface.S, surface.r, surface.q, K, T, _unpack(x), N)
        m = np.where(np.isfinite(m), m, 5.0)     # a price outside no-arb bounds is a very wrong vol, not a crash
        return w * (m - iv)

    tried = []
    best = None
    for s in starts:
        x0 = np.clip(np.array([s.v0, s.kappa, s.theta, s.sigma_v, s.rho]), BOUNDS_LO + 1e-9, BOUNDS_HI - 1e-9)
        sol = least_squares(resid, x0, bounds=(BOUNDS_LO, BOUNDS_HI), method="trf", max_nfev=max_nfev, xtol=1e-10, ftol=1e-12)
        rm = float(np.sqrt(np.mean((sol.fun / w) ** 2)))
        tried.append({"start": s, "params": _unpack(sol.x), "rmse_vol": rm, "success": bool(sol.success)})
        if best is None or rm < best[0]:
            best = (rm, sol)
    rm, sol = best
    p = _unpack(sol.x)
    res = sol.fun / w
    return CalibrationResult(p, rm, float(np.max(np.abs(res))), 2 * p.kappa * p.theta > p.sigma_v**2, int(finite.sum()),
                             evals, tuple(tried), res)
