from pathlib import Path

import pytest

from pricers import bench, cli


@pytest.fixture
def small_bench(monkeypatch):
    """Three cheap rows instead of the full table, so the harness tests run in well under a second."""
    full = bench._ours()
    monkeypatch.setattr(bench, "_ours", lambda: [full[0], full[1], full[-1]])
    monkeypatch.setattr(bench, "REPEATS", 1)
    return bench.run()


def test_bench_rows_carry_error_against_the_closed_form(small_bench):
    rows = small_bench
    assert [r.method for r in rows] == ["Black-Scholes closed form", "CRR binomial", "COS (GBM characteristic function)"]
    assert rows[0].err < 1e-12 and 0.01 < rows[1].err < 0.03 and rows[2].err < 1e-9
    assert all(r.time_ms >= 0.0 for r in rows)


def test_bench_table_is_written_between_markers_and_check_passes_then_detects_drift(small_bench, tmp_path: Path):
    readme = tmp_path / "README.md"
    readme.write_text("# x\n\nintro\n\n<!-- bench:start -->\nold\n<!-- bench:end -->\n\nafter\n")
    text = bench.table(small_bench)
    bench.write_readme(readme, text)
    out = readme.read_text()
    assert out.startswith("# x\n\nintro\n\n<!-- bench:start -->\n") and out.endswith("<!-- bench:end -->\n\nafter\n")
    assert "| CRR binomial | N=100 |" in out and "Generated by `pricers bench` on" in out
    assert bench.check_readme(readme, small_bench)
    readme.write_text(out.replace("| N=100 |", "| N=101 |"))
    assert not bench.check_readme(readme, small_bench)


def test_bench_check_ignores_times_quantlib_columns_and_mc_rows(small_bench, tmp_path: Path):
    readme = tmp_path / "README.md"
    readme.write_text("<!-- bench:start -->\n<!-- bench:end -->\n")
    bench.write_readme(readme, bench.table(small_bench))
    doctored = readme.read_text().replace(" ms |", " s |")
    readme.write_text(doctored)
    assert bench.check_readme(readme, small_bench)
    assert bench._error_cells("| MC plain (seed 42) | n=1 | 1.0 | 9.9e-01 | 1 ms | - | - | - |") == []


def test_committed_readme_table_matches_a_fresh_run_on_the_deterministic_rows():
    """The zero-spend reproducibility check CI runs; the committed README table must regenerate."""
    readme = cli.README
    assert readme.exists()
    assert bench.check_readme(readme, bench.run())


def test_cli_price_prints_black_scholes_greeks_and_each_method(capsys):
    cli.main(["price", "--S", "42", "--K", "40", "--T", "0.5", "--sigma", "0.2", "--r", "0.10"])
    out = capsys.readouterr().out
    assert out.startswith("4.759422") and "delta 0.779131" in out
    cli.main(["price", "--method", "crr", "--S", "50", "--K", "50", "--T", "0.4166667", "--sigma", "0.4", "--r", "0.1",
              "--right", "P", "--american", "--n", "5"])
    assert capsys.readouterr().out.startswith("4.488459")
    cli.main(["price", "--method", "fd-cn", "--S", "50", "--K", "50", "--T", "0.4166667", "--sigma", "0.4", "--r", "0.1",
              "--right", "P", "--american", "--n", "400"])
    assert "american bs" in capsys.readouterr().out
    cli.main(["price", "--method", "mc-cv", "--S", "100", "--K", "100", "--T", "1", "--sigma", "0.2", "--r", "0.05"])
    assert "antithetic+control_variate" in capsys.readouterr().out
    cli.main(["price", "--method", "cos-gbm", "--S", "100", "--K", "100", "--T", "1", "--sigma", "0.2", "--r", "0.05"])
    assert capsys.readouterr().out.startswith("10.450584")


def test_cli_rejects_impossible_combinations():
    with pytest.raises(SystemExit):
        cli.main(["price", "--method", "bs", "--S", "1", "--K", "1", "--T", "1", "--sigma", "0.2", "--american"])
    with pytest.raises(SystemExit):
        cli.main(["price", "--method", "lsm", "--S", "1", "--K", "1", "--T", "1", "--sigma", "0.2", "--right", "C"])
